### ISSUE TITLE
Dependency problem reproducing MNIST notebook

### ISSUE THREAD

**Issue by HosseinMA96** [google-research/jax-influence#4]
The two installation approaches provided do not work.
 The installation using the `.yml` file has not specified package versions other than python. This rises the below issue when running the second and third cell, which I could not resolve:

`Traceback (most recent call last):
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hossein/tmp/scalable influence/jax-influence/main.py", line 1, in <module>
    from jax_influence import batch_utils
  File "/home/hossein/tmp/scalable influence/jax-influence/jax_influence/batch_utils.py", line 35, in <module>
    from jax_influence.types import Array
  File "/home/hossein/tmp/scalable influence/jax-influence/jax_influence/types.py", line 36, in <module>
    import tensorflow as tf
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/tensorflow/__init__.py", line 473, in <module>
    keras._load()
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/keras/__init__.py", line 24, in <module>
    from keras import models
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/keras/engine/functional.py", line 31, in <module>
    from keras.engine import training as training_lib
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/keras/engine/training.py", line 25, in <module>
    from keras import callbacks as callbacks_module
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/keras/callbacks.py", line 49, in <module>
    import requests
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/home/hossein/anaconda3/envs/jax-influence/lib/python3.7/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
AttributeError: module 'charset_normalizer' has no attribute 'md__mypyc'

Process finished with exit code 1`

The pip installation approach also has not specified consistent flax and Jax version, which rises an error in the `linalg_utils.py`  file `AttributeError: module 'jax' has no attribute 'tree_multimap'` when running the `start_params = linalg_utils.random_initialization(params, seed=jax.random.PRNGKey(12))` line of notebook. Downgrading flax did not work.

It would be appreciated if you could provide a consistent installation method, specifying package versions.

Thanks.

**Comment by ElisaNguyen** [comment]
Hi! It worked for me after changing `tree_multimap` to `tree_map` because apparently `tree_multimap` was removed in JAX version 0.3.16. Unfortunately I couldn't find the old docs to check in the code if both functions are doing the same thing, but I would assume they do... (also, in the files of this repo I think they are only calling tree_multimap with 2 trees)

Everything in the MNIST example notebook ran smoothly when additionally installing `ml-collections, tensorflow-datasets, scikit-learn` to the libraries already specified in the .yml file.

**Comment by HosseinMA96** [comment]
Hi.
Thanks for your comment. 
I resolved it by downgrading Jax and Flax versions. I don't recall the exact versions (3.6 or 3.3) but these two also need to be compatible.
